name: 1st part

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch secrets from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://192.168.1.27:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/github-ci indexer_admin_password | INDEXER_ADMIN_PASSWORD ;
            secret/github-ci wazuh_api_password      | WAZUH_API_PASSWORD ;
            secret/github-ci kibana_user_password    | KIBANA_USER_PASSWORD ;
      - name: Render wazuh.yml from template
        run: |
          envsubst < docker/config/wazuh_dashboard/wazuh.yml.template > docker/config/wazuh_dashboard/wazuh.yml


      - name: Generate indexer certificates
        working-directory: ./docker
        run: |
          docker compose -f generate-indexer-certs.yml run --rm generator

          
      - name: Build Docker images
        working-directory: ./docker
        run: |
          docker compose up -d

      - name: Wait for Wazuh Dashboard
        run: |
          echo "⏳ Waiting for Wazuh Dashboard at https://localhost/"
          retries=30
          for i in $(seq 1 $retries); do
            body="$(curl -skL https://localhost/ || true)"
      
            if echo "$body" | grep -q "502 Bad Gateway"; then
              echo "❌ Got 502 Bad Gateway ($i/$retries)"
              sleep 5
              continue
            fi
      
            if echo "$body" | grep -q "Wazuh dashboard server is not ready yet"; then
              echo "⏳ Dashboard not ready yet... ($i/$retries)"
              sleep 5
              continue
            fi
      
            if [ -n "$body" ]; then
              echo "✅ Dashboard is ready"
              exit 0
            fi
      
            echo "Still waiting... ($i/$retries)"
            sleep 5
          done
      
          echo "❌ Timeout waiting for dashboard"
          exit 1

